export class Environments {
  static urlPattern: string = '^(https?|ftp):\/\/([a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}|localhost)(:\d{2,5})?(\/[a-zA-Z0-9._%+-\/\?=&#]*)?$';
  static baseUrl: string = 'http://localhost:8080/api';
  // static baseUrl: string = 'https://ecommerce.byserverapp.com/api';

  static frecuently: string[] = [
    'Computadora',
    'Teléfono',
    'Tablet',
    'Monitor',
    'Impresora',
    'Escáner',
    'Cámara',
    'Cable',
    'Adaptador',
    'Batería',
    'Charger',
    'Auriculares',
    'Micrófono',
    'Altavoz',
    'Cable HDMI',
    'Cable USB',
    'Cable Ethernet',
    'Cable de alimentación',
    'Disco duro',
    'Memoria RAM',
    'Procesador',
    'Ventilador',
    'Refrigerador',
    'Estufa',
    'Microondas',
    'Lavadora',
    'Secadora',
    'Aspiradora',
    'Robot aspirador',
    'Cámara de seguridad',
    'Televisor',
    'Consola de videojuegos',
    'Proyector',
    'Estación de radio',
    'Grabadora',
    'Cámara de seguridad',
    'Arroz',
    'Pollo',
    'Pasta',
    'Leche',
    'Queso',
    'Pan',
    'Té',
    'Café',
    'Agua',
    'Sal',
    'Pimienta',
    'Aceite',
    'Vinagre',
    'Azúcar',
    'Miel',
    'Harina',
    'Salchicha',
    'Huevo',
    'Atún',
    'Sopa',
    'Sándwich',
    'Pizza',
    'Tortilla',
    'Ensalada',
    'Salsa',
    'Cebolla',
    'Tomate',
    'Zanahoria',
    'Pepino',
    'Pimiento',
    'Espinaca',
    'Brócoli',
    'Remolacha',
    'Cilantro',
    'Albahaca',
    'Romero',
    'Ajo',
    'Chocolate',
    'Galletas',
    'Helado',
    'Yogur',
    'Mermelada',
    'Miel',
    'Chocolate',
    'Cerveza',
    'Vino',
    'Whisky',
    'Ron',
    'Cerveza',
    'Café'
  ];
}